# -*- coding: utf-8 -*-
"""Memoization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g5ooxnwV4d4bOKhhRgi3HflQmQ9DHXX_
"""

# Memoization is an optimization technique used primarily to speed up computer programs by storing the results of expensive function calls and returning the
#    cached results when the same input ocuur again.

# fib

import time

def fib(n):
  if n == 1 or n == 0:
    return 1
  else:
    return fib(n-1) + fib(n-2)

start = time.time()
print(fib(40))
print(time.time()-start)

# fib

import time

def fib(n,d):
  if n in d:
    return d[n]
  else:
    d[n] = fib(n-1,d) + fib(n-2,d)
    return d[n]

start = time.time()
d = {0:1,1:1}
print(fib(50,d))
print(time.time()-start)

